spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.128.13.32:3306/myproject?allowMultiQueries=true&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: remote
    password: cbt123

  redis:
    host: 43.128.13.32
    port: 6379
    database: 0
    #password:

    hikari:
      max-lifetime: 50


server:
  port: 9999

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.tao.back_project.pojo

logging:
  level:
    com.example.dao : debug